/// <reference lib="webworker" />
declare let self: ServiceWorkerGlobalScope;

import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // Intercept the POST request to the share_target action
  if (event.request.method === 'POST' && url.pathname === '/share-target') {
    event.respondWith(
      (async () => {
        try {
          const formData = await event.request.formData();
          const title = formData.get('title') || '';
          const text = formData.get('text') || '';
          const shareUrl = formData.get('url') || '';

          // Redirect to a GET route with query parameters so the frontend SPA can handle it
          const redirectUrl = `/share-target?title=${encodeURIComponent(
            title.toString()
          )}&text=${encodeURIComponent(
            text.toString()
          )}&url=${encodeURIComponent(shareUrl.toString())}`;

          return Response.redirect(redirectUrl, 303);
        } catch (error) {
          console.error('Error handling share target POST request:', error);
          return Response.redirect('/', 303);
        }
      })()
    );
  }
});
